#!/bin/sh
set -e

# -----------

cd "$(dirname "$0")/.."

# -----------

rm -rf dist
mkdir dist

# -----------

# node node_modules/.bin/jspm build ./src/app/index ./dist/app.js --format cjs --minify --no-mangle
node node_modules/.bin/jspm build ./src/app/index ./dist/app.js  --skip-source-maps

cp src/index.bundled.html dist/index.html

# -----------
