#!/bin/sh
set -e

# -----------

cd "$(dirname "$0")/.."

# -----------

rm -rf dist
mkdir dist

# -----------

node node_modules/.bin/jspm bundle-sfx ./src/app ./dist/app.js

cp src/index.bundled.html dist/index.html

# -----------
